### ISSUE TITLE
error in utils.py

### ISSUE THREAD

**Issue by notenoughtech** [sunfounder/nas-kit#2]
Error on run:

```
python raspi_omv_main.py
Traceback (most recent call last):
  File "raspi_omv_main.py", line 10, in <module>
    from utils import *
  File "/home/pi/nas-kit/main/utils.py", line 79
    print(" - %s..." % (msg), end='\r')
```

**Comment by notenoughtech** [comment]
For anyone trying this its python3 and if you get any errors,  
`sudo raspi-config`
and enable SPI interface

**Comment by Harguer** [comment]
Another important thing if you it is raspberry pi4 (guess latest update of ths OS), the python script raspi_omv_main.py is poiting to wrong location, I did somethng like this:
sudo sudo mkdir -p /opt/vc/bin/
sudo ln -s /usr/bin/vcgencmd /opt/vc/bin/vcgencmd
